-- Wild Frontier Database

DROP SCHEMA IF EXISTS WildFrontier;
CREATE SCHEMA WildFrontier;
USE wildfrontier;

CREATE TABLE Player(
player_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
username VARCHAR(30) NOT NULL,
password VARCHAR(30) NOT NULL,
email VARCHAR(45) NOT NULL, 
PRIMARY KEY (player_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Weapon(
weapon_id  INT UNSIGNED NOT NULL AUTO_INCREMENT,
weapon_name VARCHAR(30) NOT NULL,
weapon_type VARCHAR(30) NOT NULL,
upgrade_count INT NOT NULL,
PRIMARY KEY (weapon_id) 
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Player_Weapon(
player_weapon_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
player_id INT UNSIGNED NOT NULL,
weapon_id INT UNSIGNED NOT NULL,
weapon_damage INT UNSIGNED NOT NULL,
PRIMARY KEY (player_weapon_id),
CONSTRAINT FOREIGN KEY (player_id) REFERENCES Player (player_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT FOREIGN KEY (weapon_id) REFERENCES Weapon (weapon_id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Item_inventory (
item_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
item_name VARCHAR(30) NOT NULL,
item_type VARCHAR(30) NOT NULL,
PRIMARY KEY (item_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Player_Item(
player_item_id  INT UNSIGNED NOT NULL AUTO_INCREMENT,
player_id INT UNSIGNED NOT NULL,
item_id INT UNSIGNED NOT NULL,
quantity INT UNSIGNED NOT NULL,
PRIMARY KEY (player_item_id),
CONSTRAINT FOREIGN KEY (player_id) REFERENCES Player (player_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT FOREIGN KEY (item_id) REFERENCES Item_inventory (item_id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Player_Status(
player_status_id  INT UNSIGNED NOT NULL AUTO_INCREMENT,
player_id INT UNSIGNED NOT NULL,
current_level INT UNSIGNED NOT NULL,
last_checkpoint INT UNSIGNED NOT NULL,
PRIMARY KEY (player_status_id),
CONSTRAINT FOREIGN KEY (player_id) REFERENCES Player (player_id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Checkpoint_Death(
checkpoint_death_id INT UNSIGNED NOT NULL AUTO_INCREMENT, 
checkpoint INT UNSIGNED NOT NULL,
player_id INT UNSIGNED NOT NULL,
player_lose_count INT UNSIGNED NOT NULL,
PRIMARY KEY (checkpoint_death_id),
CONSTRAINT FOREIGN KEY (player_id)  REFERENCES Player (player_id)  ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Death_Type(
death_type_id  INT UNSIGNED NOT NULL AUTO_INCREMENT, 
death_type VARCHAR(15) NOT NULL,
PRIMARY KEY (death_type_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Player_Death(
player_death_id  INT UNSIGNED NOT NULL AUTO_INCREMENT,
player_status_id INT UNSIGNED NOT NULL,
death_type_id INT UNSIGNED NOT NULL,
death_type_count INT UNSIGNED NOT NULL,
PRIMARY KEY (player_death_id),
CONSTRAINT FOREIGN KEY (player_status_id) REFERENCES Player_Status (player_status_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT FOREIGN KEY (death_type_id) REFERENCES Death_Type (death_type_id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

